name: test

on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'renv'
    - uses: r-lib/actions/setup-renv@v2
    - name: Install trachoma model and dependencies
      run: pip install git+https://github.com/NTD-Modelling-Consortium/ntd-model-trachoma.git@master
    - name: Install AMIS integration package
      run: pip install .
    - name: Run Python tests
      run: python -m pytest tests/
    - name: Run top-level script
      # run: Rscript trachoma_fitting.R
      run: echo Disable running script until we have a test case
